# Generated by Django 6.0.2 on 2026-02-09 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TastingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="평점",
                    ),
                ),
                ("tasted_date", models.DateField(verbose_name="시음일")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("home", "집"),
                            ("restaurant", "레스토랑"),
                            ("bar", "바"),
                            ("event", "이벤트"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="장소 유형",
                    ),
                ),
                (
                    "location_detail",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="장소 상세"
                    ),
                ),
                (
                    "appearance_clarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clear", "맑음"),
                            ("hazy", "흐림"),
                            ("cloudy", "탁함"),
                        ],
                        max_length=20,
                        verbose_name="투명도",
                    ),
                ),
                (
                    "appearance_intensity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="색 강도",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="색상 설명"
                    ),
                ),
                (
                    "aroma_intensity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="향 강도",
                    ),
                ),
                (
                    "aroma_notes",
                    models.TextField(blank=True, verbose_name="아로마 노트"),
                ),
                (
                    "body",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="바디",
                    ),
                ),
                (
                    "acidity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="산도",
                    ),
                ),
                (
                    "tannin",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="타닌",
                    ),
                ),
                (
                    "sweetness",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="당도",
                    ),
                ),
                (
                    "pairing",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="페어링 음식"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="커스텀 필드 값"
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="S3 등 URL 리스트. 로컬 개발 시 미디어 경로",
                        verbose_name="사진 URL 목록",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="공개 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "시음 노트",
                "verbose_name_plural": "시음 노트",
                "db_table": "tasting_notes",
                "ordering": ["-tasted_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="템플릿명")),
                (
                    "fields",
                    models.JSONField(
                        default=dict,
                        help_text='커스텀 필드 목록. 예: {"fields": [{"name": "pairing", "type": "text", "label": "페어링 음식"}, {"name": "appearance_notes", "type": "text", "label": "외관 메모"}, {"name": "aroma_tags", "type": "tags", "label": "아로마 태그"}]}',
                        verbose_name="필드 정의",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 사용"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "시음 노트 템플릿",
                "verbose_name_plural": "시음 노트 템플릿",
                "db_table": "templates",
                "ordering": ["-updated_at"],
            },
        ),
    ]
