# Generated by Django 6.0.2 on 2026-02-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notes", "0001_initial"),
        ("wines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tastingnote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasting_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tastingnote",
            name="wine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasting_notes",
                to="wines.wine",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tastingnote",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasting_notes",
                to="notes.template",
            ),
        ),
        migrations.AddIndex(
            model_name="tastingnote",
            index=models.Index(
                fields=["user", "-tasted_date"], name="tasting_not_user_id_4432ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tastingnote",
            index=models.Index(fields=["wine"], name="tasting_not_wine_id_ad4399_idx"),
        ),
        migrations.AddIndex(
            model_name="tastingnote",
            index=models.Index(
                fields=["is_public"], name="tasting_not_is_publ_57cc77_idx"
            ),
        ),
    ]
