# Generated by Django 6.0.2 on 2026-02-09 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="와인명")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("red", "레드"),
                            ("white", "화이트"),
                            ("rose", "로제"),
                            ("sparkling", "스파클링"),
                            ("champagne", "샴페인"),
                            ("dessert", "디저트 와인"),
                            ("fortified", "주정강화"),
                            ("orange", "오렌지 와인"),
                            ("natural", "내추럴 와인"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="종류",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="산지(지역)"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="WINE_COUNTRY_CHOICES 또는 자유 입력",
                        max_length=100,
                        verbose_name="국가",
                    ),
                ),
                (
                    "vintage",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2027),
                        ],
                        verbose_name="빈티지",
                    ),
                ),
                (
                    "grape_varieties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="예: ['Cabernet Sauvignon', 'Merlot']",
                        verbose_name="품종",
                    ),
                ),
                (
                    "alcohol_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="도수",
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="평균 가격",
                    ),
                ),
                (
                    "winery",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="와이너리"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="외부 API ID (Wine-Searcher 등)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
            options={
                "verbose_name": "와인",
                "verbose_name_plural": "와인",
                "db_table": "wines",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="wines_name_acd91f_idx"),
                    models.Index(fields=["winery"], name="wines_winery_351a54_idx"),
                    models.Index(fields=["type"], name="wines_type_09b482_idx"),
                    models.Index(fields=["region"], name="wines_region_d74ca4_idx"),
                    models.Index(fields=["country"], name="wines_country_addcd1_idx"),
                ],
            },
        ),
    ]
